### PR TITLE
fix: Fix borken migration.

### PR DESCRIPTION
**Pull request by merlin-northern**
Changelog: Title
Ticket: MEN-5719
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by merlin-northern** [comment]
to be consistent I did it exactly like we have in deviceconnect.

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Review by kjaskiewiczz — APPROVED** [review]
looks good

**Comment by merlin-northern** [comment]
tested with 1025 devices.

**Comment by merlin-northern** [comment]
the failure in mtls is a know one, un related.

**Comment by merlin-northern** [comment]
@mender-test-bot cherry-pick to:
 * 3.0.x
 please

**Comment by merlin-northern** [comment]
@mender-test-bot cherry-pick to:
* 1.1.x
please

**Pull request merged**
