### PR TITLE
Change device ID data type from uuid.UUID to string

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by tranchitella** [comment]
Uhm, it needs a double-check as it doesn't seem to compile.

**Comment by alfrunes** [comment]
Sorry, I accidentally broke it when fixing the static check error. It should be all good now.

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]

**Comment by alfrunes** [comment]
@tranchitella I rebased this PR on top of master, which dismissed your review. Can you please have a quick look?

**Review by tranchitella — APPROVED** [review]

**Comment by alfrunes** [comment]
@tranchitella can you help me merge it as well? There's no point running the QA pipeline for this change.

**Pull request merged**
