### PR TITLE
extend endpoint for deploying configuration with support for optional update control map parameter

### PR DESCRIPTION
**Pull request by kjaskiewiczz**
https://tracker.mender.io/browse/MEN-4553

### CODE REVIEW

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]

**Review by alfrunes — APPROVED** [review]

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Comment by kjaskiewiczz** [comment]
@mender-test-bot start pipeline

**Review by tranchitella — APPROVED** [review]
Thanks for the nice clean-ups!

**Pull request merged**
